<?php

namespace EllipticCurve\Test;
use EllipticCurve\Test\TestCase;

echo "\n\nRunning OpenSSL tests:";
\Test\printHeader("OpenSSL");


class TestOpenSSL extends TestCase
{
    public function testAssign()
    {
        // Generated by: openssl ecparam -name secp256k1 -genkey -out privateKey.pem
        $privateKeyPem = \EllipticCurve\Utils\File::read("tests/privateKey.pem");

        $privateKey = \EllipticCurve\PrivateKey::fromPem($privateKeyPem);

        $message = \EllipticCurve\Utils\File::read("tests/message.txt");

        $signature = \EllipticCurve\Ecdsa::sign($message, $privateKey);

        $publicKey = $privateKey->publicKey();

        \Test\assertTrue(\EllipticCurve\Ecdsa::verify($message, $signature, $publicKey));
    }

    public function testVerifySignature()
    {
        // openssl ec -in privateKey.pem -pubout -out publicKey.pem
        $publicKeyPem = \EllipticCurve\Utils\File::read("tests/publicKey.pem");

        // openssl dgst -sha256 -sign privateKey.pem -out signature.binary message.txt
        $signatureDer = \EllipticCurve\Utils\File::read("tests/signatureDer.txt", "rb");

        $message = \EllipticCurve\Utils\File::read("tests/message.txt");

        $publicKey = \EllipticCurve\PublicKey::fromPem($publicKeyPem);

        $signature = \EllipticCurve\Signature::fromDer($signatureDer);

        \Test\assertTrue(\EllipticCurve\Ecdsa::verify($message, $signature, $publicKey));
    }
}


$tests = new TestOpenSSL();
$tests->run();
